<<<<<<< HEAD
controller_joint_names: ['', 'joint_1', 'joint_2', 'joint_3', 'joint_4', 'gripper_joint', ]
=======
controller_joint_names: ['', 'joint_1', 'joint_2', 'joint_3', 'joint_4', 'gripper_joint', ]
>>>>>>> 8eb6b2d0975f0746757bb3a666b8c3111cffaf8d
